### ISSUE TITLE
Permission issues 

### ISSUE THREAD

**Issue by Mailblocker** [cewood/mbsync-docker#2]
Hi,
I'm getting the following message when running your image:

    bsync                   | time="2021-01-03T19:25:00Z" level=info msg="Maildir error: cannot create mailbox '/workdir/test-backup/INBOX': Permission denied" channel=stderr iteration=0 job.command="mbsync -a" job.position=0 job.schedule="* * * * *"

Do I have to add a special user to the host machine running docker?

Thank you!

**Comment by cewood** [comment]
> Hi,
> I'm getting the following message when running your image:
> 
> ```
> bsync                   | time="2021-01-03T19:25:00Z" level=info msg="Maildir error: cannot create mailbox '/workdir/test-backup/INBOX': Permission denied" channel=stderr iteration=0 job.command="mbsync -a" job.position=0 job.schedule="* * * * *"
> ```

The image runs as the Mbsync user, which has the uid/gid of 1000. So you have two options, chown/chmod the directory(s) in question on your host system to allow access when they are bind mounted in the container. And/or you could pass the `user` flag to docker and run the container as another user/uid to match the permissions of the directory/files you're mounting in. Personally I only use the former, since the uid/gid of 1000 is already matching my host system user.

> Do I have to add a special user to the host machine running docker?

No, this isn't necessary. See above.

**Comment by Mailblocker** [comment]
Alright, since I got a dedictaed user to run my docker I will go with the user flag and set it accordingly.

Thank you!

**Comment by Mailblocker** [comment]
Okay after some fiddling around I got it working with setting my UID and GID.

Here is an extract of my docker-compose file:

    mbsync:
        container_name: mbsync
        image: cewood/mbsync:alpine_latest
        restart: always
        user: ${UID}:${GID}
        volumes:
          - ${LOCAL_MBSYNC_DATA}:/data
          - ${LOCAL_MBSYNC_CONFIG}/mbsyncrc:/.mbsyncrc
          - ${LOCAL_MBSYNC_CONFIG}/crontab:/etc/crontab

extract of my mbsync config:

    MaildirStore    web-local
    Path            /data/test-backup/
    Inbox           /data/test-backup/INBOX


@cewood As you can see I took out the `working_dir: /workdir` since it is created with the owner mbsync which is UID 1000. At the same time the cronjob is using `/` as the working dir with a user id != 1000 since there is no home folder defined in this case. Therefore I moved .mbsyncrc to `/`, otherwise the cron job is not able to access the config file.

Is this the correct way/a valid configuration?

**Comment by cewood** [comment]
> Is this the correct way/a valid configuration?

If it works for you I guess that's all that matters, it looks fine to me.

My only comment/critique, would be I'd personally avoid putting things under `/` just by habit/convention.


> ```
> mbsync:
>     container_name: mbsync
>     image: cewood/mbsync:alpine_latest
>     restart: always
>     user: ${UID}:${GID}
>     volumes:
>       - ${LOCAL_MBSYNC_DATA}:/data
>       - ${LOCAL_MBSYNC_CONFIG}/mbsyncrc:/.mbsyncrc
>       - ${LOCAL_MBSYNC_CONFIG}/crontab:/etc/crontab
> ```

In my personal config, I create the data dir as a sub-directory of `/workdir`, but to do that the data dir should have suitable permissions to allow either mbsync (1000:1000) or whatever other user you want to run the container as, to read and write files in that dir. The parent `/workdir` folder doesn't interfere with this, so long as the `data` dir has the right permissions for the user you run the container as.

Below is an example of a `docker run` command you can use to easily experiment with this. After you run the docker command, you'll be dropped into a bash shell, where you'll see if you run `id` or `whoami` that you're running as user `1111` as expected (no name is returned, since we didn't actually create this user, but that's not important). And if you try creating a file, say with `touch data/example1` you'll be able to create said file, and it will appear in your data2 folder with the expected permissions/ownership.

```
$ mkdir data2 && sudo chown 1111:1111 data2
$ docker run --rm -it -v $PWD/mbsyncrc:/workdir/.mbsyncrc -v $PWD/crontab:/etc/crontab -v $PWD/data2:/workdir/data -w /workdir --user 1111:1111 cewood/mbsync:alpine_latest bash
```

Below is another example, this time using `mbsync`. You'll notice I pass the `--config` option to `mbsync` here, this is because we're not using a "real" user anymore, and hence there is no HOME environment variable for it to use to find the config automatically, so we need to tell it where by explicitly passing the `--config` flag. You could probably also do this by specifying a HOME environment variable as well, but the flag seemed easier and more straight forward.

```
$ docker run --rm -it -v $PWD/mbsyncrc:/workdir/.mbsyncrc -v $PWD/crontab:/etc/crontab -v $PWD/data2:/workdir/data -w /workdir --user 1111:1111 cewood/mbsync:alpine_latest mbsync --config /workdir/.mbsyncrc --all --list
```

Hope this helps.

**Comment by Mailblocker** [comment]
Your comment helped a lot. I did not like the working in the root directory myself but I just did not see the option `--config` for mbsync.

Got it up and running now with the working_dir. Thanks a lot!
